parameters:
#    luxon_cms.example.class: Luxon\Bundle\CmsBundle\Example

services:
#    luxon_cms.example:
#        class: %luxon_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
