<?php

namespace Luxon\Bundle\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NodeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeTypeRepository extends EntityRepository
{
}
